version: '3.1'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: memes_user
      POSTGRES_PASSWORD: memes_pass
      POSTGRES_DB: memes_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memes_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: